Добавил проверку запуска OpenKore

diff --git a/.github/workflows/build_XSTools.yml b/.github/workflows/build_XSTools.yml
--- a/.github/workflows/build_XSTools.yml
+++ b/.github/workflows/build_XSTools.yml
@@ -442,6 +442,19 @@ jobs:
       run: |
         make test
 
+    ###################
+    # OpenKore launch #
+    ###################
+
+    - name: Start OpenKore
+      run: |
+        perl ./openkore.pl --version
+        if [ $? -eq 0 ] then
+          echo "Successfully"
+        else
+          echo "Error: $?"
+        fi
+
   #######################
   # start the third job #
   #######################
