добавил проверку на винде

diff --git a/.github/workflows/build_XSTools.yml b/.github/workflows/build_XSTools.yml
--- a/.github/workflows/build_XSTools.yml
+++ b/.github/workflows/build_XSTools.yml
@@ -171,7 +171,7 @@ jobs:
     - name: Making artifacts
       uses: actions/upload-artifact@v3
       with:
-        name: ${{ matrix.os }}_perl-${{ matrix.perl }}${{ matrix.architecture }}
+        name: XSTools_${{ matrix.os }}_perl-${{ matrix.perl }}${{ matrix.architecture }}
         path: |
           src\auto\XSTools\XSTools_notes.txt
           src\auto\XSTools\XSTools.dll
@@ -251,7 +251,7 @@ jobs:
     - name: Restoring XTools from artifacts
       uses: actions/download-artifact@v3
       with:
-        name: ${{ matrix.os }}_perl-${{ matrix.perl }}${{ matrix.architecture }}
+        name: XSTools_${{ matrix.os }}_perl-${{ matrix.perl }}${{ matrix.architecture }}
 
     - name: Checking for XSTools
       shell: bash
@@ -267,6 +267,19 @@ jobs:
       run: |
         cd src\test
         perl unittests.pl
+
+    ###################
+    # OpenKore launch #
+    ###################
+
+    - name: Start OpenKore
+      run: |
+        perl ./openkore.pl --version
+        if ( $? -eq "True" ) {
+          echo "OpenKore started successfully"
+        } else {
+          echo "Error: $LASTEXITCODE"
+        }
 
 
 ###################
@@ -450,7 +463,7 @@ jobs:
       run: |
         perl ./openkore.pl --version
         if [ $? -eq 0 ] then
-          echo "Successfully"
+          echo "OpenKore started successfully"
         else
           echo "Error: $?"
         fi
